g1-e-commerce.json
src/app/api/components/ContributorsList.js
src/app/api/page.js
src/app/globals.css

JSON data file has been added and tested with the endpoint of /api.
For now we have almot all of the deta we need in order to display for the MVP.
I will continue working on GutHub app and secret key to be able retriving the Project Cards data.

Generating the json file

---

g1-e-commerce.json
src/app/components/ProjectCard.js
src/app/components/TasksActivity.js
src/app/components/TeamOverviewHeader.js
src/app/page.js

Please review my changes.
- I created the table using data from json file
- I altered the json file, for closed/open issues so I can render both, as all issues for that specific project were all open.
- I implemented the feature to scroll over the table so it displays only 4 tasks.

Lorena task activity #7

---

package-lock.json
package.json
src/app/components/TeamActivity.js

there is commented version of the component in case we need just simple version:
and example of the chart that you can see currently (we will edit it once agree the design):
I've installed chart.js for this PR
Note - Team Overview is not styled properly, but it should be a seperate ticket. WE will discuss this tommorow

Natalia team activity card #3 - completed MVP

---

package-lock.json
src/app/components/ProjectCard.js

Mo project card continuation #2

---

app/page.js

I did not change the background color of the sidebar, as it should be changed with the Dark/Light Mode feature. I suggest designing the Teams page initially in light Mode as in the wireframe

Created the skeleton fronted of the Teams pages

---

app/page.js

It seems that the code has changed a little bit after merging. I fixed it and it should work now on Netlify. @momahboobian thank you for raising the issue!

fix the issue after merging

---

.eslintrc.json
package-lock.json
package.json

Fixing the eslint and npm version

---

app/api/page.js
components/GroupsPage.js
components/OverallInfoCard.js
components/ProjectCard.js
components/Sidebar.js
components/SidebarDarkMode.js
components/SidebarDashboard.js
components/SidebarLogo.js
components/SidebarTeams.js
components/TasksActivity.js
components/TeamActivity.js
components/TeamOverviewHeader.js

Now card project is back to the dashboard page

Mo node and eslint config

---

app/dashboard/page.js
app/page.js
components/GroupsPage.js
components/TeamCard.js

I have improved the design for the _last update_ and _pull requests_.  The number of PRs and the date is hardcoded. There is no JSON file yet, but I am happy to create if nobody is already working on it.
Also, I haven't included the "..." button, as we have agreed this is not for an MVP.
Currently, the design looks like this:
Maybe we can highlight the PR number:
`<div className="text-center text-[18px] font-bold ">
<div className="text-[#37BCBA] bg-black rounded-full w-7  mx-auto">
15
</div>
</div>`
But this is just a suggestion, I did not include the second style :) 
Please let me know what do you think and if any changes are required!

Natalie design team card #42

---

components/ProjectCard.js
components/TeamOverviewHeader.js
pages/api/gitHubAPI.js

Please review my changes.
> I decreased the run time to less than 1 minute.
> I set up the Loading state.
> I added an animation while loading is true.
> I rendered the cards for trainees only.

Lorena Fetch Time #56 

---

components/TaskActivityPie.js

Updating style for the pie and bar chart #66 
Names on the pie chart now not overlapping

Updating style for the pie and bar chart #66

---

app/dashboard/page.js
app/my-tasks/page.js
app/page.js
app/statistics/page.js
components/ComingSoon.js
components/OverallInfoCard.js
components/ProjectCard.js
components/Sidebar.js
components/SidebarDashboard.js
components/TaskActivityPie.js
components/TasksActivity.js
components/TeamOverviewHeader.js

In this pr I have managed to update a few style issue
Also Fix the table Task Activity
And Added comingsoon to the My Task and Statistic page

Fixing the cards and removing buttuns#78

---

app/page.js
components/GroupsPage.js
components/TeamCard.js
groups.json
styles/globals.css

Please check the team-page. 
No additional dependencies.

Lorena team cards styling completion #81

---

pages/api/gitHubAPI.js

- I created a cache object which stores all the requests for 30 mins.
- Hence, I set an interval which updated the data every half an hour.
- data caching positively impacted the run time which is around **20ms**
Test by keep refreshing the dashboard. 
_**Code explaination:**_
The **getCached** function checks if the cached item exists and if the elapsed time since caching is within the expiration time. If the cached item is valid, it returns the cached data. 
Otherwise, it makes a request to fetch the data, updates the cache with the new data and the current timestamp, and returns the response.

Lorena caching data #91

---

components/GroupsPage.js
components/TeamCard.js
package-lock.json
package.json

Reverts nataliiazab/good-pr#96

Revert "Natalie link the team page with the database #84"

---

components/GroupsPage.js
components/TeamCard.js
components/TeamOverviewHeader.js
pages/api/gitHubAPI.js

Only the team cards from db are in this PR.
No additional API requests

Lorena team page&db

---

components/TeamCard.js
pages/api/gitHubAPI.js
prisma/schema.prisma

Lorena pr&last update

---

app/page.js
components/GroupsPage.js

I adjusted the cards size so it fit inside Team's Page.
from this:
To this

Lorena fit team cards into page #127

---

components/GroupsPage.js
components/TeamCard.js
tailwind.config.js

Natalie team page GitHub icon to have random neon style#86

---

components/TeamActivityPie.js
components/Tooltips.js

Add individual number of PRs + Add Tool tip to the Piechart

Farnoosh individual number of p rs #142

---

components/Sidebar.js

Ensure the hamburger menu closes when clicking outside of it.
Change the hamburger menu icon to X when the sidebar is open

Farnoosh closing hamburger menu 147

---

components/ProjectCard.js
components/TasksActivity.js
components/TeamCard.js
components/TeamOverviewHeader.js

Thanks to an amazing @LorenaCapraru 
And also thanks to @ehwus

Mo toggle table #138

---

components/GroupsPage.js
components/ShareButton.js
components/TasksActivity.js
components/TeamCard.js
components/TeamOverviewHeader.js

Mo fixing table and team cards
